--2023.04.03. ¿ÀÀü
DROP TABLE ADDRESS;
DROP TABLE EDUCATION_LEVEL;
DROP TABLE GRADE;
DROP TABLE INTEREST;
DROP TABLE MESSAGE2;
DROP TABLE RANKING;
DROP TABLE HOUR_STUDY;
DROP TABLE STUDY_CAFE;
DROP TABLE STUDY_TIME;
DROP TABLE USERS;
DROP PROCEDURE ADD_USER;
DROP PROCEDURE ADD_USER_LOG;
DROP PROCEDURE INSERT_RANKING;
DROP PROCEDURE INSERT_STUDY_TIME;
DROP PROCEDURE PRINT_RANKING;
DROP PROCEDURE SEND_MESSAGE;